### ISSUE TITLE
Build Failed to start

### ISSUE THREAD

**Issue by choyan** [Nine-H/apollo11#6]
Whenever I try to start the build, it shows an error and can't start anymore.

> ~/Public/apollo11/build
❯ ./apollo11 
[INFO 21:56:56.347505] Application.vala:155: Apollo11 version: (null)
[INFO 21:56:56.347545] Application.vala:157: Kernel version: 4.4.0-62-generic
[ERROR 21:56:56.350785] [GLib-GIO] Settings schema 'com.github.nine-h.apollo11' is not installed
[1]    22431 trace trap (core dumped)  ./apollo11

**Comment by Nine-H** [comment]
in this case you need to run `sudo make install` to add the relevant gsettings schemas to your system. you can find what schemas are installed by opening /data/com.github.nine-h.apollo11.gschema.xml this will also let you add more settings to the application and save settings.
